<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-29B4KFL" failures="3" tests="4" name="Test" time="100.0" errors="0" timestamp="2024-05-03T19:58:54 IST">
  <testcase classname="com.facebook.Testcases.LoginTestCases" name="loginTest" time="23.579"/>
  <testcase classname="com.facebook.Testcases.LoginTestCases" name="loginTest" time="25.097">
    <failure type="java.lang.AssertionError" message="Login Not Successfully done expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Not Successfully done expected [true] but found [false]
at com.facebook.Testcases.LoginTestCases.loginTest(LoginTestCases.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.facebook.Testcases.LoginTestCases" name="loginTest" time="22.521">
    <failure type="java.lang.AssertionError" message="Login Not Successfully done expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Not Successfully done expected [true] but found [false]
at com.facebook.Testcases.LoginTestCases.loginTest(LoginTestCases.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.facebook.Testcases.LoginTestCases" name="loginTest" time="26.851">
    <failure type="java.lang.AssertionError" message="Login Not Successfully done expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Not Successfully done expected [true] but found [false]
at com.facebook.Testcases.LoginTestCases.loginTest(LoginTestCases.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test -->
